#! /bin/bash
#==========================================================================
# File            : path
# Description     : 
# @(#) Path check
#
# Revision History: 
#
#   10 Jul 2017 - sijegana
#      Initial Version.
#==========================================================================
checkPath "${PATH}" 
