#! /bin/bash
#==========================================================================
# File            : today
# Description     : 
# @(#) print today date
#
# Revision History: 
#
#   05 Aug 2017 - sijegana
#      Initial Version.
#==========================================================================
date  '+%Y-%m-%d'
